namespace StateMachineLibrary.SourceGenerators.Emission;

public static class DeclarationApiSource
{
    public const string HintName = "StateMachineDeclarationApi.g.cs";

    public const string Source = """
                                 // <auto-generated />
                                 #nullable enable
                                 namespace StateMachineLibrary.SourceGeneration
                                 {
                                     /// <summary>Declares the state and event types for a generated finite state machine definition.</summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                                     internal sealed class StateMachineAttribute : global::System.Attribute
                                     {
                                         /// <summary>Creates a state machine declaration.</summary>
                                         public StateMachineAttribute(global::System.Type stateType, global::System.Type eventType)
                                         {
                                             StateType = stateType;
                                             EventType = eventType;
                                         }

                                         /// <summary>The state value type.</summary>
                                         public global::System.Type StateType { get; }

                                         /// <summary>The event value or payload base type.</summary>
                                         public global::System.Type EventType { get; }
                                     }

                                     /// <summary>Declares a state value for a generated finite state machine definition.</summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
                                     internal sealed class StateAttribute : global::System.Attribute
                                     {
                                         /// <summary>Creates a state declaration.</summary>
                                         public StateAttribute(object value) => Value = value;

                                         /// <summary>The declared state value.</summary>
                                         public object Value { get; }

                                         /// <summary>Marks the state as terminal.</summary>
                                         public bool IsTerminal { get; set; }
                                     }

                                     /// <summary>Declares a simple event value or payload event type.</summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
                                     internal sealed class EventAttribute : global::System.Attribute
                                     {
                                         /// <summary>Creates a simple event value declaration.</summary>
                                         public EventAttribute(object value) => Value = value;

                                         /// <summary>Creates a payload event type declaration.</summary>
                                         public EventAttribute(global::System.Type payloadType) => PayloadType = payloadType;

                                         /// <summary>The simple event value.</summary>
                                         public object? Value { get; }

                                         /// <summary>The payload event type.</summary>
                                         public global::System.Type? PayloadType { get; }
                                     }

                                     /// <summary>Declares a transition between states.</summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
                                     internal sealed class TransitionAttribute : global::System.Attribute
                                     {
                                         /// <summary>Creates a transition for a simple event value.</summary>
                                         public TransitionAttribute(object sourceState, object eventValue, object targetState)
                                         {
                                             SourceState = sourceState;
                                             EventValue = eventValue;
                                             TargetState = targetState;
                                         }

                                         /// <summary>Creates a transition for a payload event type.</summary>
                                         public TransitionAttribute(object sourceState, global::System.Type eventType, object targetState)
                                         {
                                             SourceState = sourceState;
                                             EventType = eventType;
                                             TargetState = targetState;
                                         }

                                         /// <summary>The transition source state.</summary>
                                         public object SourceState { get; }

                                         /// <summary>The simple event value.</summary>
                                         public object? EventValue { get; }

                                         /// <summary>The payload event type.</summary>
                                         public global::System.Type? EventType { get; }

                                         /// <summary>The transition target state.</summary>
                                         public object TargetState { get; }

                                         /// <summary>The transition kind.</summary>
                                         public TransitionKind Kind { get; set; }

                                         /// <summary>Condition member name.</summary>
                                         public string? Condition { get; set; }

                                         /// <summary>Transition behavior member name.</summary>
                                         public string? Behavior { get; set; }
                                     }

                                     /// <summary>Transition kind used by declaration attributes.</summary>
                                     internal enum TransitionKind { External, Self, Internal }

                                     /// <summary>Metadata key/value declaration.</summary>
                                     [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
                                     internal sealed class MetadataAttribute : global::System.Attribute
                                     {
                                         /// <summary>Creates metadata for the machine declaration.</summary>
                                         public MetadataAttribute(string key, object? value)
                                         {
                                             Key = key;
                                             Value = value;
                                         }

                                         /// <summary>Metadata key.</summary>
                                         public string Key { get; }

                                         /// <summary>Metadata value.</summary>
                                         public object? Value { get; }
                                     }

                                     /// <summary>Declarative DSL entry type parsed by the source generator and never executed during generation.</summary>
                                     internal sealed class StateMachineDeclaration<TState, TEvent>
                                     {
                                         /// <summary>Declares definition metadata.</summary>
                                         public StateMachineDeclaration<TState, TEvent> WithMetadata(string key, object? value) => this;
                                         /// <summary>Declares or configures a state.</summary>
                                         public StateDeclaration<TState, TEvent> State(TState value) => new StateDeclaration<TState, TEvent>();
                                     }

                                     /// <summary>Declarative DSL state builder marker.</summary>
                                     internal sealed class StateDeclaration<TState, TEvent>
                                     {
                                         /// <summary>Marks the state terminal.</summary>
                                         public StateDeclaration<TState, TEvent> Terminal() => this;
                                         /// <summary>Declares state metadata.</summary>
                                         public StateDeclaration<TState, TEvent> WithMetadata(string key, object? value) => this;
                                         /// <summary>Starts a simple event transition declaration.</summary>
                                         public TransitionDeclaration<TState, TEvent> On(TEvent eventValue) => new TransitionDeclaration<TState, TEvent>();
                                         /// <summary>Starts a payload event transition declaration.</summary>
                                         public TransitionDeclaration<TState, TEvent> On<TSpecificEvent>() where TSpecificEvent : TEvent => new TransitionDeclaration<TState, TEvent>();
                                     }

                                     /// <summary>Declarative DSL transition builder marker.</summary>
                                     internal sealed class TransitionDeclaration<TState, TEvent>
                                     {
                                         /// <summary>Declares a condition member reference.</summary>
                                         public TransitionDeclaration<TState, TEvent> When(string memberName, string? displayName = null) => this;
                                         /// <summary>Declares exit behavior member reference.</summary>
                                         public TransitionDeclaration<TState, TEvent> OnExit(string memberName, string? displayName = null) => this;
                                         /// <summary>Declares transition behavior member reference.</summary>
                                         public TransitionDeclaration<TState, TEvent> Execute(string memberName, string? displayName = null) => this;
                                         /// <summary>Declares entry behavior member reference.</summary>
                                         public TransitionDeclaration<TState, TEvent> OnEntry(string memberName, string? displayName = null) => this;
                                         /// <summary>Declares transition metadata.</summary>
                                         public TransitionDeclaration<TState, TEvent> WithMetadata(string key, object? value) => this;
                                         /// <summary>Completes an external transition to a target state.</summary>
                                         public StateDeclaration<TState, TEvent> GoTo(TState targetState) => new StateDeclaration<TState, TEvent>();
                                         /// <summary>Completes a self transition.</summary>
                                         public StateDeclaration<TState, TEvent> Self() => new StateDeclaration<TState, TEvent>();
                                         /// <summary>Completes an internal transition.</summary>
                                         public StateDeclaration<TState, TEvent> Internal() => new StateDeclaration<TState, TEvent>();
                                     }
                                 }
                                 """;
}