using System.Text;
using Microsoft.CodeAnalysis;
using StateMachineLibrary.SourceGenerators.Declarations;

namespace StateMachineLibrary.SourceGenerators.Emission;

public static class DefinitionSourceEmitter
{
    public static string Emit(MachineDeclaration declaration)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        var namespaceName = declaration.ContainingType.ContainingNamespace?.IsGlobalNamespace == false
            ? declaration.ContainingType.ContainingNamespace.ToDisplayString()
            : null;
        if (namespaceName is not null)
        {
            sb.Append("namespace ").Append(namespaceName).AppendLine();
            sb.AppendLine("{");
        }

        var containingTypes = GetContainingTypes(declaration.ContainingType).ToArray();
        var indentLevel = namespaceName is null ? 0 : 1;
        foreach (var containingType in containingTypes)
        {
            AppendIndentedLine(sb, indentLevel, GetTypeDeclaration(containingType));
            AppendIndentedLine(sb, indentLevel, "{");
            indentLevel++;
        }

        AppendIndentedLine(sb, indentLevel, GetTypeDeclaration(declaration.ContainingType));
        AppendIndentedLine(sb, indentLevel, "{");
        var memberIndent = Indent(indentLevel + 1);
        sb.Append(DefinitionMemberEmitter.EmitMembers(declaration.StateTypeName, declaration.EventTypeName,
            EmitCreateBody(declaration), memberIndent));
        sb.Append(EventHelperEmitter.Emit(declaration, memberIndent));
        sb.Append(GeneratedMetadataEmitter.Emit(declaration, memberIndent));
        sb.Append(GeneratedGraphEmitter.Emit(declaration, memberIndent));
        AppendIndentedLine(sb, indentLevel, "}");

        for (var i = containingTypes.Length - 1; i >= 0; i--)
        {
            indentLevel--;
            AppendIndentedLine(sb, indentLevel, "}");
        }

        if (namespaceName is not null) sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitCreateBody(MachineDeclaration declaration)
    {
        var sb = new StringBuilder();
        var definitionType = "global::StateMachineLibrary.Core.Definitions.StateMachineDefinition<" +
                             declaration.StateTypeName + ", " + declaration.EventTypeName + ">";
        sb.Append("return ").Append(definitionType).AppendLine(".Create(machine =>");
        sb.AppendLine("{");

        foreach (var metadata in declaration.Metadata)
            sb.Append("    machine.WithMetadata(").Append(ConditionReferenceEmitter.Literal(metadata.Key)).Append(", ")
                .Append(metadata.ValueExpression).AppendLine(");");

        sb.Append("    machine.WithMetadata(\"SourceGeneration.DeclarationStyle\", ")
            .Append(ConditionReferenceEmitter.Literal(declaration.DeclarationStyle.ToString())).AppendLine(");");

        foreach (var state in declaration.States)
        {
            sb.Append("    machine.State(").Append(state.ValueExpression).Append(")");
            if (state.ParentStateExpression is not null) sb.Append(".ChildOf(").Append(state.ParentStateExpression).Append(")");
            if (state.InitialChildExpression is not null) sb.Append(".InitialChild(").Append(state.InitialChildExpression).Append(")");
            if (state.HistoryMode is DeclaredHistoryMode.Shallow or DeclaredHistoryMode.Deep)
            {
                sb.Append(".WithHistory(")
                    .Append(AdvancedDeclarationParserHelpers.CoreHistoryMode(state.HistoryMode));
                if (state.HistoryFallbackExpression is not null)
                    sb.Append(", ").Append(state.HistoryFallbackExpression);
                sb.Append(")");
            }

            if (state.IsParallelComposite) sb.Append(".ParallelComposite()");
            if (state.IsTerminal) sb.Append(".Terminal()");

            sb.Append(MetadataEmitter.Emit(state.Metadata));
            sb.AppendLine(";");
        }

        foreach (var region in CanonicalRegions(declaration))
            EmitRegion(sb, declaration, region);

        foreach (var completion in declaration.CompletionDeclarations)
        {
            if (declaration.States.Any(s => s.IdentityKey == completion.SourceStateKey) &&
                declaration.States.Any(s => s.IdentityKey == completion.TargetStateKey))
                sb.Append("    machine.State(").Append(completion.SourceExpression).Append(").OnCompletion().GoTo(")
                    .Append(completion.TargetExpression).AppendLine(");");
        }

        foreach (var transition in declaration.Transitions)
        {
            var source = declaration.States.FirstOrDefault(s => s.IdentityKey == transition.SourceStateKey);
            var declaredEvent = declaration.Events.FirstOrDefault(e => e.IdentityKey == transition.EventKey);
            if (source is null || declaredEvent is null) continue;

            sb.Append("    machine.State(").Append(source.ValueExpression).Append(")");
            if (declaredEvent.EventKind == DeclaredEventKind.PayloadType)
                sb.Append(".On<").Append(declaredEvent.PayloadType).Append(">()");
            else
                sb.Append(".On(").Append(declaredEvent.ValueExpression).Append(")");

            foreach (var condition in transition.Conditions) sb.Append(ConditionReferenceEmitter.Emit(condition));

            foreach (var behavior in transition.Behaviors) sb.Append(BehaviorReferenceEmitter.Emit(behavior));

            sb.Append(MetadataEmitter.Emit(transition.Metadata));
            if (transition.TransitionKind == DeclaredTransitionKind.Self)
                sb.Append(".Self()");
            else if (transition.TransitionKind == DeclaredTransitionKind.Internal)
                sb.Append(".Internal()");
            else
                sb.Append(".GoTo(").Append(transition.TargetExpression).Append(")");

            sb.AppendLine(";");
        }

        sb.AppendLine("});");
        return sb.ToString();
    }

    private static IEnumerable<RegionDeclaration> CanonicalRegions(MachineDeclaration declaration)
    {
        return declaration.Regions
            .GroupBy(r => (r.OwnerCompositeStateKey, r.RegionName))
            .Select(g => g.OrderBy(r => r.Order).First())
            .OrderBy(r => r.Order);
    }

    private static void EmitRegion(StringBuilder sb, MachineDeclaration declaration, RegionDeclaration region)
    {
        if (region.InitialStateExpression is null) return;

        var memberships = declaration.RegionMemberships
            .Where(m => m.OwnerCompositeStateKey == region.OwnerCompositeStateKey &&
                        string.Equals(m.RegionName, region.RegionName, StringComparison.Ordinal))
            .ToArray();
        var memberExpressions = memberships
            .Select(m => m.StateExpression)
            .Where(e => !string.Equals(e, region.InitialStateExpression, StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        var terminalExpressions = memberships
            .Where(m => m.IsTerminal)
            .Select(m => m.StateExpression)
            .Distinct(StringComparer.Ordinal)
            .ToArray();

        sb.Append("    machine.ParallelComposite(").Append(region.OwnerCompositeExpression).Append(")")
            .Append(".Region(")
            .Append(ConditionReferenceEmitter.Literal(region.RegionName)).Append(", ")
            .Append(region.InitialStateExpression).Append(", ")
            .Append(ArrayExpression(memberExpressions, declaration.StateTypeName)).Append(", ")
            .Append(ArrayExpression(terminalExpressions, declaration.StateTypeName)).AppendLine(");");
    }

    private static string ArrayExpression(IReadOnlyList<string> expressions, string elementType)
    {
        return expressions.Count == 0
            ? "global::System.Array.Empty<" + elementType + ">()"
            : "new " + elementType + "[] { " + string.Join(", ", expressions) + " }";
    }

    private static IEnumerable<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol type)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var current = type.ContainingType; current is not null; current = current.ContainingType)
            stack.Push(current);

        return stack;
    }

    private static void AppendIndentedLine(StringBuilder builder, int indentLevel, string line)
    {
        builder.Append(Indent(indentLevel)).AppendLine(line);
    }

    private static string Indent(int indentLevel)
    {
        return new string(' ', indentLevel * 4);
    }

    private static string GetTypeDeclaration(INamedTypeSymbol type)
    {
        var accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" :
            type.DeclaredAccessibility == Accessibility.Internal ? "internal" : string.Empty;
        var kind = type.TypeKind == TypeKind.Struct ? "struct" : "class";
        var staticModifier = type.IsStatic ? " static" : string.Empty;
        var typeParameters = type.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", type.TypeParameters.Select(p => p.Name)) + ">";

        return (accessibility + staticModifier + " partial " + kind + " " + type.Name + typeParameters).Trim();
    }
}